// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN10lL-zgcXlz4uPq6XcH-0txGKboL94Q',
    appId: '1:927516748258:web:3dfcffaa43d661ef32f1bb',
    messagingSenderId: '927516748258',
    projectId: 'capstone-15e06',
    authDomain: 'capstone-15e06.firebaseapp.com',
    storageBucket: 'capstone-15e06.appspot.com',
    measurementId: 'G-4MKZHB5DZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6OrerabcTvBsZTXvhHW8rloAPnU-GSs',
    appId: '1:927516748258:android:b9cc45c3adbc612632f1bb',
    messagingSenderId: '927516748258',
    projectId: 'capstone-15e06',
    storageBucket: 'capstone-15e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1T1S70TyxEhnnTOekPNkW6d95Hqr5LaU',
    appId: '1:927516748258:ios:cdd5911aa9a7421d32f1bb',
    messagingSenderId: '927516748258',
    projectId: 'capstone-15e06',
    storageBucket: 'capstone-15e06.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1T1S70TyxEhnnTOekPNkW6d95Hqr5LaU',
    appId: '1:927516748258:ios:220d303a66a771c332f1bb',
    messagingSenderId: '927516748258',
    projectId: 'capstone-15e06',
    storageBucket: 'capstone-15e06.appspot.com',
    iosBundleId: 'com.example.capstone.RunnerTests',
  );
}
